name: blade-geometry
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pyvista
  - vtk
  - pythonocc-core=7.7.*
  - occt=7.7.*
  - jsonschema
  - pip
  - pip:
      - tqdm